/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ChatResponseSourceMetadata } from "./chatResponseSourceMetadata"

export type ChatResponse = {
  answer: string
  source_content: string
  source_metadata: ChatResponseSourceMetadata
}
