/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DocsInfo } from "./docsInfo"

export type DocsUploadOutSchema = {
  docsInfo: DocsInfo
  type: string
}
